name: Main
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:
jobs:
  fetch_and_push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Get UUP dump CLI
        run: |
          git clone --depth=1 --single-branch --branch=master --recurse-submodules https://git.uupdump.net/uup-dump/standalone.git
          mv standalone/* .
          rm -rf standalone/.git
          mv standalone/.* .
          rmdir standalone
      - name: Get Windows 10 versions
        run: |
          set -x
          php fetchdetect.php all Retail Mainline 17763 1 125 Production
          php fetchdetect.php all Retail Mainline 19044 1288 125 Production
          php fetchdetect.php all Retail Mainline 19045 2006 4 Production
      - name: Get Windows 11 versions
        run: |
          set -x
          php fetchdetect.php all Retail Mainline 22621 382 4 Production
          php fetchdetect.php all Retail Mainline 22631 2428 4 Production
          php fetchdetect.php all Retail Mainline 26100 2 125 Production
      - name: Push packs & fileinfos
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add fileinfo
          git add packs
          git commit -m "feat: upload fileinfo + packs"
          git push
